### ISSUE TITLE
Add Basic Git Commands

### ISSUE THREAD

**Issue by piyush9311** [piyush9311/All_About_Github#1]

**Comment by Abhir-24** [comment]
Can i work on this?

**Comment by mohitrakhade20** [comment]
Kindly assigned this issue to me,  I started repo and ready to contribute

**Comment by piyush9311** [comment]
See if anyone of yours PR for hactoberfest is done give other a chance

**Comment by Abhir-24** [comment]
mine is not done yet

**Comment by mohitrakhade20** [comment]
Okay then I will do the advance git command issue #7

**Comment by piyush9311** [comment]
Ya sure

**Comment by mohitrakhade20** [comment]
Can I add the Basic git command in a better way?
